# coding: utf-8

module ONIX; module CodeLists
  LIST_33 = {
    "01" => "Main description",
    "02" => "Short description/annotation",
    "03" => "Long description",
    "04" => "Table of contents",
    "05" => "Review quote, restricted length",
    "06" => "Quote from review of previous edition",
    "07" => "Review text",
    "08" => "Review quote",
    "09" => "Promotional \"headline\"",
    "10" => "Previous review quote",
    "11" => "Author comments",
    "12" => "Description for reader",
    "13" => "Biographical note",
    "14" => "Description for Reading Group Guide",
    "15" => "Discussion question for Reading Group Guide",
    "16" => "Competing titles",
    "17" => "Flap copy",
    "18" => "Back cover copy",
    "19" => "Feature",
    "20" => "New feature",
    "21" => "Publisher's notice",
    "23" => "Excerpt from book",
    "24" => "First chapter",
    "25" => "Description for sales people",
    "26" => "Description for press or other media",
    "27" => "Description for subsidiary rights department",
    "28" => "Description for teachers/educators",
    "30" => "Unpublished endorsement",
    "31" => "Description for bookstore",
    "32" => "Description for library",
    "33" => "Introduction or preface",
    "34" => "Full text",
    "35" => "Promotional text",
    "40" => "Author interview / QandA",
    "41" => "Reading Group Guide",
    "42" => "Commentary / discussion",
    "99" => "Country of final manufacture"
  }
end; end